//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeveGen.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeveGen.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alchemist.
        /// </summary>
        public static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Armorer.
        /// </summary>
        public static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blacksmith.
        /// </summary>
        public static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearBtn {
            get {
                return ResourceManager.GetString("ClearBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Carpenter.
        /// </summary>
        public static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Culinarian.
        /// </summary>
        public static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exp Reward.
        /// </summary>
        public static string ExpReward {
            get {
                return ResourceManager.GetString("ExpReward", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goldsmith.
        /// </summary>
        public static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HqOnly.
        /// </summary>
        public static string HqOnly {
            get {
                return ResourceManager.GetString("HqOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HqOnlyDesc.
        /// </summary>
        public static string HqOnlyDesc {
            get {
                return ResourceManager.GetString("HqOnlyDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LeveName.
        /// </summary>
        public static string LeveName {
            get {
                return ResourceManager.GetString("LeveName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leatherworker.
        /// </summary>
        public static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate Lisbeth Orders.
        /// </summary>
        public static string MakeLizbeth {
            get {
                return ResourceManager.GetString("MakeLizbeth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Lisbeth orders for the selected leves. If Optimize EXP is checked, it will create orders based on how many HQ items are required to get to the next tier of Leves, otherwise it will create orders to complete 5 leves..
        /// </summary>
        public static string MakeLizbethDesc {
            get {
                return ResourceManager.GetString("MakeLizbethDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to # of Repeats.
        /// </summary>
        public static string NumRepeat {
            get {
                return ResourceManager.GetString("NumRepeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optimize Exp.
        /// </summary>
        public static string OptimizeExp {
            get {
                return ResourceManager.GetString("OptimizeExp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only do the leve for it&apos;s level range. This is to maximize EXP.
        /// </summary>
        public static string OptimizeExpDesc {
            get {
                return ResourceManager.GetString("OptimizeExpDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to # of Items.
        /// </summary>
        public static string qtyItem {
            get {
                return ResourceManager.GetString("qtyItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveBtn {
            get {
                return ResourceManager.GetString("RemoveBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saves the profile if you want to use it later.
        /// </summary>
        public static string SaveTooltip {
            get {
                return ResourceManager.GetString("SaveTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartBtn {
            get {
                return ResourceManager.GetString("StartBtn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tradecraft.
        /// </summary>
        public static string Tradecraft {
            get {
                return ResourceManager.GetString("Tradecraft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weaver.
        /// </summary>
        public static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
    }
}
