//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeveGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeveGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Leves&quot;: [
        ///    {
        ///      &quot;LeveId&quot;: 21,
        ///      &quot;Name&quot;: &quot;In with the New&quot;,
        ///      &quot;Classes&quot;: &quot;Carpenter&quot;,
        ///      &quot;Level&quot;: 1,
        ///      &quot;ExpReward&quot;: 728,
        ///      &quot;Repeats&quot;: 0,
        ///      &quot;PickUpNpc&quot;: 1000101,
        ///      &quot;TurnInNpc&quot;: 1001276,
        ///      &quot;NumItems&quot;: 1,
        ///      &quot;ItemId&quot;: 1820,
        ///      &quot;ItemName&quot;: &quot;Bone Harpoon&quot;
        ///    },
        ///    {
        ///      &quot;LeveId&quot;: 81,
        ///      &quot;Name&quot;: &quot;Red in the Head&quot;,
        ///      &quot;Classes&quot;: &quot;Leatherworker&quot;,
        ///      &quot;Level&quot;: 1,
        ///      &quot;ExpReward&quot;: 480,
        ///      &quot;Repeats&quot;: 0,
        ///      &quot;PickUpNpc&quot;: 1000101,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///             xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///             xmlns:L=&quot;clr-namespace:LeveGen.Localization&quot;
        ///             mc:Ignorable=&quot;d&quot;
        ///              Background=&quot;white&quot;
        ///             d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;600&quot;&gt;
        ///    &lt;Grid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
    }
}
